### ISSUE TITLE
Добавить включение бота

### ISSUE THREAD

**Issue by elfishkate** [skar404/sputnik_bot#40]
По фразе формата: "Доброе утро", "поехали"

**Comment by skar404** [comment]
Я предлагаю немного изменить алгоритм включения бота, 

---

Добавить теги утром в которые будут добавлю фразы:

'доброе утро', 'поехали', 'доброе', 'утро', 'хочу спать'

---

1. Бот видел что неделю назад был рабочий день или прислан тег утро
2. он сам пишет доброе утро* и присылает мотивирующие фото
2.1. На сообщения есть кнопка чтобы сказать что это не рабочий день  
3. Начинает отправлять новости 

> \* бот будет просыпаться примерно в ~5:30 но будте зависит
