### ISSUE TITLE
Предложения по улучшению

### ISSUE THREAD

**Issue by elfishkate** [skar404/sputnik_bot#63]
Поступило ЦУ резко сократить количество отправляемых новостей до 20-25 за смену.
Идея: к уведомлению добавить подпись, которая показывала бы, какая по счету новость ушла в вейбо. 
Пример: Я успешно отправил в вейбо, 7\25 
Так будет удобно отслеживать количество отправленных в вейбо новостей и понимать, сколько еще их можно будет закинуть.

**Comment by skar404** [comment]
Добали в текст успешной отправки в Weibo еще количетво успешных сообщений:

Пример текста:
```
Сегодня я уже отправил {send_count}/25 постов
Я успешно отправил в weibo, время: {end_time}
```

Плюс доабвил такойже текст для каждой новосте отправляемый в TG

---

Также для полчения статистики отпарвленных постов можно воспользоваться командой `/statistics`:

<img width="379" alt="Screenshot 2019-07-22 at 04 02 57" src="https://user-images.githubusercontent.com/8483941/61599877-9d12a600-ac35-11e9-9770-53c714ef9643.png">
